### ISSUE TITLE
Possible to add group attributes?

### ISSUE THREAD

**Issue by relrod** [fedora-infra/freeipa-fas#7]
No hard requirement here yet, but something to explore/consider: Is it possible to add group attributes in a similar way to the user attributes done already here?

Current FAS groups store:
* url
* mailing list
* mailing list url
* irc channel
* irc network
* rules for membership

Some/all of these might not be necessary any more (and we could probably just tell people to use the description field for them) -- but if we do decide to keep them, is it any harder to add than the user attributes were?

**Comment by ryanlerch** [comment]
Is this a big thing to add?

**Comment by tiran** [comment]
No, it's simple. Just tell me what you need exactly.

For IRC channel I'd rather use a single multi-value attribute where each attribute entry encodes IRC network and channel. Perhaps like https://www.w3.org/Addressing/draft-mirashi-url-irc-01.txt ?

**Comment by ryanlerch** [comment]
@abompard probably should confirm, but the following fields should be added:

* ```URL``` -- a url for the group. Typically in the fedoraproject, this is a link to the group's Wiki page.
* ```mailing list``` -- a mailing list address, for example: fedora-infrastructure-list@redhat.com
* ```mailing list url``` -- the mailman url for the mailing list.
* ```irc```

I think we can probably drop the rules for membership.

With IRC, i am happy to use a single attribute here (rather than a multi-value), but still encoding the netwerok and channel as suggested above. IMHO, most groups really only have one irc channel here.

**Comment by abompard** [comment]
I think we can drop `mailing_list_url` and generate that ourselves in Noggin from the list's address.

**Comment by ryanlerch** [comment]
Okies, so really 3 fields here:

* URL
* Mailing List Address
* IRC channel / server
